/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/purchases/purchases`; params?: Router.UnknownInputParams; } | { pathname: `/changes/changes`; params?: Router.UnknownInputParams; } | { pathname: `/changes/new-change`; params?: Router.UnknownInputParams; } | { pathname: `/purchases/new-purchase`; params?: Router.UnknownInputParams; } | { pathname: `/changes/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/purchases/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/teamCalendar` | `/teamCalendar`; params?: Router.UnknownInputParams; } | { pathname: `/tasks/new-task`; params?: Router.UnknownInputParams; } | { pathname: `/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/purchases/purchases`; params?: Router.UnknownOutputParams; } | { pathname: `/changes/changes`; params?: Router.UnknownOutputParams; } | { pathname: `/changes/new-change`; params?: Router.UnknownOutputParams; } | { pathname: `/purchases/new-purchase`; params?: Router.UnknownOutputParams; } | { pathname: `/changes/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/purchases/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/teamCalendar` | `/teamCalendar`; params?: Router.UnknownOutputParams; } | { pathname: `/tasks/new-task`; params?: Router.UnknownOutputParams; } | { pathname: `/tasks/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/purchases/purchases${`?${string}` | `#${string}` | ''}` | `/changes/changes${`?${string}` | `#${string}` | ''}` | `/changes/new-change${`?${string}` | `#${string}` | ''}` | `/purchases/new-purchase${`?${string}` | `#${string}` | ''}` | `/changes/[id]${`?${string}` | `#${string}` | ''}` | `/purchases/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/teamCalendar${`?${string}` | `#${string}` | ''}` | `/teamCalendar${`?${string}` | `#${string}` | ''}` | `/tasks/new-task${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/purchases/purchases`; params?: Router.UnknownInputParams; } | { pathname: `/changes/changes`; params?: Router.UnknownInputParams; } | { pathname: `/changes/new-change`; params?: Router.UnknownInputParams; } | { pathname: `/purchases/new-purchase`; params?: Router.UnknownInputParams; } | { pathname: `/changes/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/purchases/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/teamCalendar` | `/teamCalendar`; params?: Router.UnknownInputParams; } | { pathname: `/tasks/new-task`; params?: Router.UnknownInputParams; } | `/tasks/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
