create type "public"."purchase_status" as enum ('pending', 'purchased', 'delivered');

create type "public"."task_category" as enum ('electricidad', 'plomeria', 'construccion', 'pintura');

create type "public"."task_status" as enum ('completed', 'pending', 'blocked', 'in_progress', 'changes', 'rejected');

create type "public"."user_role" as enum ('admin', 'client');

create table "public"."belongs_to" (
    "user_id" uuid not null,
    "site_id" uuid not null,
    "role" user_role not null default 'client'::user_role
);


create table "public"."profiles" (
    "id" uuid not null,
    "name" text not null,
    "avatar_url" text,
    "whatsapp_jid" text
);


create table "public"."purchases" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "site_id" uuid not null,
    "user_id" uuid not null,
    "product" text not null,
    "description" text default 'Sin descripción'::text,
    "quantity" smallint not null default '1'::smallint,
    "price" real,
    "supplier" text,
    "category" task_category not null,
    "status" purchase_status not null,
    "purchase_date" timestamp with time zone,
    "delivery_date" timestamp with time zone
);


create table "public"."site" (
    "address" text not null,
    "created_at" date not null default now(),
    "id" uuid not null default gen_random_uuid()
);


create table "public"."task_dependencies" (
    "blocker_id" uuid,
    "blocked_id" uuid
);


create table "public"."tasks" (
    "user_id" uuid not null default auth.uid(),
    "created_at" timestamp without time zone not null default now(),
    "title" text not null,
    "description" text,
    "status" task_status not null default 'pending'::task_status,
    "category" task_category,
    "start_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "site_id" uuid not null,
    "id" uuid not null default gen_random_uuid()
);


create table "public"."updates" (
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "title" text not null,
    "description" text,
    "image_url" text,
    "id" uuid not null default gen_random_uuid(),
    "site_id" uuid not null
);


create table "public"."workers_contacts" (
    "owner_id" uuid not null,
    "worker_fullname" text not null default ''::text,
    "worker_cellnumber" text not null default ''::text,
    "profession" text not null default '"other"'::text
);


CREATE UNIQUE INDEX belongs_to_pkey ON public.belongs_to USING btree (user_id, site_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX purchases_pkey ON public.purchases USING btree (id);

CREATE UNIQUE INDEX site_id_key ON public.site USING btree (id);

CREATE UNIQUE INDEX site_pkey ON public.site USING btree (id);

CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id);

CREATE UNIQUE INDEX updates_id_key ON public.updates USING btree (id);

CREATE UNIQUE INDEX updates_pkey ON public.updates USING btree (id, site_id);

CREATE UNIQUE INDEX workers_contacts_pkey ON public.workers_contacts USING btree (owner_id, worker_cellnumber);

alter table "public"."belongs_to" add constraint "belongs_to_pkey" PRIMARY KEY using index "belongs_to_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."purchases" add constraint "purchases_pkey" PRIMARY KEY using index "purchases_pkey";

alter table "public"."site" add constraint "site_pkey" PRIMARY KEY using index "site_pkey";

alter table "public"."tasks" add constraint "tasks_pkey" PRIMARY KEY using index "tasks_pkey";

alter table "public"."updates" add constraint "updates_pkey" PRIMARY KEY using index "updates_pkey";

alter table "public"."workers_contacts" add constraint "workers_contacts_pkey" PRIMARY KEY using index "workers_contacts_pkey";

alter table "public"."belongs_to" add constraint "belongs_to_site_id_fkey" FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."belongs_to" validate constraint "belongs_to_site_id_fkey";

alter table "public"."belongs_to" add constraint "belongs_to_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."belongs_to" validate constraint "belongs_to_user_id_fkey1";

alter table "public"."profiles" add constraint "profiles_full_name_check" CHECK ((char_length(name) >= 3)) not valid;

alter table "public"."profiles" validate constraint "profiles_full_name_check";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."purchases" add constraint "purchases_site_id_fkey" FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."purchases" validate constraint "purchases_site_id_fkey";

alter table "public"."purchases" add constraint "purchases_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."purchases" validate constraint "purchases_user_id_fkey";

alter table "public"."site" add constraint "site_id_key" UNIQUE using index "site_id_key";

alter table "public"."task_dependencies" add constraint "task_dependencies_blocked_id_fkey" FOREIGN KEY (blocked_id) REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_blocked_id_fkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_blocker_id_fkey" FOREIGN KEY (blocker_id) REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_blocker_id_fkey";

alter table "public"."tasks" add constraint "tasks_site_id_fkey" FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "tasks_site_id_fkey";

alter table "public"."tasks" add constraint "tasks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "tasks_user_id_fkey";

alter table "public"."updates" add constraint "updates_id_key" UNIQUE using index "updates_id_key";

alter table "public"."updates" add constraint "updates_site_id_fkey" FOREIGN KEY (site_id) REFERENCES site(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."updates" validate constraint "updates_site_id_fkey";

alter table "public"."updates" add constraint "updates_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."updates" validate constraint "updates_user_id_fkey1";

alter table "public"."workers_contacts" add constraint "workers_contacts_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."workers_contacts" validate constraint "workers_contacts_owner_id_fkey";

alter table "public"."workers_contacts" add constraint "workers_contacts_profession_check" CHECK ((length(profession) < 40)) not valid;

alter table "public"."workers_contacts" validate constraint "workers_contacts_profession_check";

alter table "public"."workers_contacts" add constraint "workers_contacts_worker_cellnumber_check" CHECK ((length(worker_cellnumber) < 20)) not valid;

alter table "public"."workers_contacts" validate constraint "workers_contacts_worker_cellnumber_check";

alter table "public"."workers_contacts" add constraint "workers_contacts_worker_fullname_check" CHECK ((length(worker_fullname) < 50)) not valid;

alter table "public"."workers_contacts" validate constraint "workers_contacts_worker_fullname_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_task_dependencies()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  if new.status = 'completed' and old.status <> 'completed' then
    update public.tareas
    set status = 'pending'
    where
      id in (
        select blocked_id
        from public.task_dependencies
        where blocker_id = old.id
      )

      and not exists (
        select 1
        from public.task_dependencies as deps
        join public.tareas as tarea_bloqueadora on deps.blocker_id = tarea_bloqueadora.id
        where
          deps.blocked_id = tareas.id
          and tarea_bloqueadora.status <> 'completed'
      );
      end if;
      return new;
      end;
      $function$
;

create policy "Allow insert for authenticated"
on "public"."belongs_to"
as permissive
for insert
to public
with check ((auth.uid() = user_id));


create policy "Allow service role read access"
on "public"."belongs_to"
as permissive
for select
to public
using (((auth.role() = 'service_role'::text) OR (auth.uid() = user_id)));


create policy "Profiles: delete all"
on "public"."profiles"
as permissive
for delete
to public
using (true);


create policy "Profiles: insert own"
on "public"."profiles"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = id));


create policy "Profiles: select own"
on "public"."profiles"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = id));


create policy "Profiles: update own"
on "public"."profiles"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = id))
with check ((( SELECT auth.uid() AS uid) = id));


create policy "Enable read access for all users"
on "public"."tasks"
as permissive
for select
to public
using (true);




